#-----------------------------------------------------------------------

MINIFE_TYPES =  \
        -DMINIFE_SCALAR=double   \
        -DMINIFE_LOCAL_ORDINAL=int      \
        -DMINIFE_GLOBAL_ORDINAL=int

MINIFE_MATRIX_TYPE = -DMINIFE_CSR_MATRIX
# MINIFE_MATRIX_TYPE = -DMINIFE_ELL_MATRIX

#-----------------------------------------------------------------------
OPT_FLAGS = -O3 -g
OTHER_INCLUDE = -I/users/misc/sjinang/papi-install/include
CFLAGS  += $(OPT_FLAGS) $(OTHER_INCLUDE)
CXXFLAGS = $(CFLAGS)

CPPFLAGS = -I. -I../utils -I../fem $(MINIFE_TYPES) $(MINIFE_MATRIX_TYPE) \
	-DHAVE_MPI -DMPICH_IGNORE_CXX_SEEK \
	-DMINIFE_REPORT_RUSAGE

OTHER_LIB = /users/misc/sjinang/papi-install/lib/libpapi.a

LDFLAGS += $(OTHER_LIB)
LIBS=

CXX=mpicxx
CC=mpicc

#CXX=g++
#CC=gcc

include make_targets

